ERROR_MESSAGES = {
    "AuthException": [
        "There was a problem receiving your Pocket list...",
        "The workflow has been deauthorized automatically. Please try again!",
    ],
    "URLError": [
        "Could not connect to getpocket.com...",
        "Please check your Internet connection and try again!",
    ],
    "PocketException": [
        "Could not receive your Pocket list...",
        "Please try again or file a bug report!",
    ],
    "PasswordNotFound": [
        "Could not find access token...",
        "Please try again or file a bug report!",
    ],
}
